"use client";

import { motion } from "framer-motion";
import { Brain, Cpu, Bot, Sparkles } from "lucide-react";

export default function AISection() {
  return (
    <section id="ai-research" className="py-32 relative overflow-hidden">
      {/* Background Glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-neon-purple/20 blur-[120px] rounded-full pointer-events-none" />

      <div className="container mx-auto px-6 relative z-10">
        <motion.div
           initial={{ opacity: 0, scale: 0.9 }}
           whileInView={{ opacity: 1, scale: 1 }}
           viewport={{ once: true }}
           className="bg-card-bg backdrop-blur-xl border border-black/5 dark:border-neon-purple/30 rounded-3xl p-8 md:p-16 text-center max-w-4xl mx-auto shadow-[0_0_50px_rgba(185,103,255,0.1)]"
        >
          <div className="inline-flex items-center justify-center p-3 bg-neon-purple/20 rounded-xl mb-6 text-neon-purple">
             <Brain className="w-8 h-8" />
          </div>
          
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-6">Exploring <span className="text-neon-purple">Artificial Intelligence</span></h2>
          <p className="text-slate-muted text-lg leading-relaxed mb-10 max-w-2xl mx-auto">
            My current focus lies at the intersection of backend engineering and AI. I am actively researching and building with Large Language Models (LLMs), RAG architectures, and autonomous agents.
          </p>

          <div className="grid md:grid-cols-3 gap-6">
            <div className="p-4 rounded-xl bg-white/5 border border-white/5 hover:border-neon-purple/50 transition-colors">
              <Bot className="w-6 h-6 text-neon-purple mb-3 mx-auto" />
              <h3 className="text-foreground font-medium mb-1">AI Agents</h3>
              <p className="text-sm text-slate-400">Building autonomous task-solvers.</p>
            </div>
            <div className="p-4 rounded-xl bg-white/5 border border-white/5 hover:border-neon-purple/50 transition-colors">
              <Cpu className="w-6 h-6 text-neon-purple mb-3 mx-auto" />
              <h3 className="text-foreground font-medium mb-1">RAG Systems</h3>
              <p className="text-sm text-slate-400">Enhancing LLMs with custom data.</p>
            </div>
            <div className="p-4 rounded-xl bg-white/5 border border-white/5 hover:border-neon-purple/50 transition-colors">
              <Sparkles className="w-6 h-6 text-neon-purple mb-3 mx-auto" />
              <h3 className="text-foreground font-medium mb-1">Generative UI</h3>
              <p className="text-sm text-slate-400">Dynamic interfaces generated by AI.</p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
